version: "3.9"

services:
  build-awscdk-minecraft-frontend:
    command: "'[[ -d ./node_modules ]] || (npm install --force && npm audit fix);  npm run build'"
    entrypoint: /bin/bash -c
    image: awscdk-minecraft/ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    # environment:
    # for "process.env.REACT_" variables in react code that need to be substituted
