version: "3.9"

services:
  build-rootski-frontend:
    command: build
    image: awscdk-minecraft/ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    # environment:
    # for "process.env.REACT_" variables in react code that need to be substituted
