version: "3.7"

services:
  minecraft:
    # image docs: https://github.com/itzg/docker-minecraft-server
    image: itzg/minecraft-server
    restart: always
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      TYPE: PAPER
      VERSION: ${MINECRAFT_SERVER_SEMANTIC_VERSION:-1.19}
      MINMEM: "hi"
      MAXMEM: "no"
    networks:
      - minecraft-server
    deploy:
      replicas: 1

networks:
  minecraft-server:
    driver: overlay
    name: minecraft-server
    attachable: true
